adminUser:
  password: vault:pr-473-2arc/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:pr-473-2arc/pipelineUser:token
  username: arcalos-bot
prow:
  hmacToken: vault:pr-473-2arc/prow:hmacToken
segmentWriteKey: vault:pr-473-2arc:segmentWriteKey
